version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: habbo-api
      MYSQL_USER: root
      MYSQL_PASSWORD: BobbaHobba
    volumes:
      - db_data:/var/lib/mysql/data
  app:
    depends_on:
      - db
    build: .
    ports:
      - 3000
    restart: always
    environment:
      PORT: 3000
      DB_HOST: db
      DB_NAME: habbo-api
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: BobbaHobba
volumes:
  db_data: