version: '3'
services:
  app:
    image: vulture:plus
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    restart: always
    environment:
      EMULATOR: plus
      PORT: 3000
      DB_HOST: db
      DB_NAME: plus-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: XdnVdCBnMVpDC3He
